namespace Kokos.Compiler.Syntax;

public enum TokenKind
{
    EndOfFile,
    Bad,

    Identifier,
    NumberLiteral,
    StringLiteral,

    // Keywords
    FunctionKeyword,
    LetKeyword,
    ReturnKeyword,
    TypeKeyword,
    OpaqueKeyword,
    EnumKeyword,
    StructKeyword,
    ValueKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    ThenKeyword,
    TrueKeyword,
    FalseKeyword,
    OwnedKeyword,
    UnownedKeyword,
    ManualKeyword,
    UnmanagedKeyword,
    DestroyedKeyword,
    FreeKeyword,
    ImportKeyword,
    ExportKeyword,

    // Punctuation
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Comma,
    Colon,
    Semicolon,
    Dot,
    Question,
    Pipe,
    Hash,

    // Operators
    Equals,
    EqualsEquals,
    Bang,
    BangEquals,
    Plus,
    Minus,
    Star,
    Slash,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    AmpAmp,
    PipePipe,
}
